[package]
name="minesweeper"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","boogie2","js"]

[build.whiley]
verify=false

[build.boogie]
verbose=true
verify=true

[build.js]
standard="ES6"
target="public/js"

[check]
min=-3
max=3
length=3
depth=1

[dependencies]
dom="0.1.0"
