[package]
name="minesweeper"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js"]

[build.whiley]
verify=false

[check]
min=-2
max=2
length=3
depth=1

[dependencies]
std="0.2.10"
