[package]
name="minesweeper"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js"]

[build.whiley]
verify=false

[build.js]
standard="ES6"

[check]
min=-3
max=3
length=3
depth=1

[dependencies]
std="0.2.10"
