[package]
name="minesweeper"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","boogie","js"]

[build.boogie]
timeout=300

[build.js]
standard="ES6"
target="public/js"

[check]
min=-3
max=3
length=3
depth=1

[dependencies]
dom="0.2.2"
js="0.1.7"
std="0.3.2"
